spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: loadout-service
          uri: lb://LOADOUT-SERVICE
          predicates:
            - Path=/loadout/**
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**
        - id: provider-service
          uri: lb://PROVIDER-SERVICE
          predicates:
            - Path=/group/**
        - id: provider-service
          uri: lb://PROVIDER-SERVICE
          predicates:
            - Path=/role/**
        - id: provider-service
          uri: lb://PROVIDER-SERVICE
          predicates:
            - Path=/provider/**
server:
  port: 5010

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://84.86.167.197:8761/eureka/
  instance:
    hostname: localhost
